### ISSUE TITLE
Appendix DjangoProject - ModuleNotFoundError: No module named 'alloc'

### ISSUE THREAD

**Issue by dmgolembiowski** [cosmicpython/code#38]
## Description
`make all` fails during pytest step.

## Demonstration
```sh
$ make all
docker-compose down --remove-orphans
Removing cosmic-python_postgres_1 ... done
Removing network cosmic-python_default
docker-compose build
postgres uses an image, skipping
WARNING: Native build is an experimental feature and could change at any time
Building app
[+] Building 0.5s (13/13) FINISHED                                                                                                                                                                                
 => [internal] load build definition from Dockerfile                                                                                                                                                         0.0s
 => => transferring dockerfile: 38B                                                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                                                            0.1s 
 => => transferring context: 2B                                                                                                                                                                              0.0s 
 => [internal] load metadata for docker.io/library/python:3.9-slim-buster                                                                                                                                    0.3s 
 => [internal] load build context                                                                                                                                                                            0.0s
 => => transferring context: 2.18kB                                                                                                                                                                          0.0s 
 => [1/8] FROM docker.io/library/python:3.9-slim-buster@sha256:182f0eff727af9fccf88294dbfffb23ad408369c412e1267ddd5aa63ef8b5bf8                                                                              0.0s 
 => CACHED [2/8] COPY requirements.txt /tmp/                                                                                                                                                                 0.0s 
 => CACHED [3/8] RUN pip install -r /tmp/requirements.txt                                                                                                                                                    0.0s 
 => CACHED [4/8] RUN mkdir -p /src                                                                                                                                                                           0.0s 
 => CACHED [5/8] COPY src/ /src/                                                                                                                                                                             0.0s 
 => CACHED [6/8] RUN pip install -e /src                                                                                                                                                                     0.0s 
 => CACHED [7/8] COPY tests/ /tests/                                                                                                                                                                         0.0s 
 => CACHED [8/8] WORKDIR /src                                                                                                                                                                                0.0s 
 => exporting to image                                                                                                                                                                                       0.1s 
 => => exporting layers                                                                                                                                                                                      0.0s
 => => writing image sha256:9566a0aa0ba5691e04eaa23ea011c4047413369f81d62e4eca26c9f7528927be                                                                                                                 0.0s 
 => => naming to docker.io/library/cosmic-python_app                                                                                                                                                         0.0s
Successfully built 9566a0aa0ba5691e04eaa23ea011c4047413369f81d62e4eca26c9f7528927be
docker-compose up -d app
WARNING: Native build is an experimental feature and could change at any time
Creating network "cosmic-python_default" with the default driver
Creating cosmic-python_postgres_1 ... done
Creating cosmic-python_app_1      ... done
docker-compose run --rm --no-deps --entrypoint=pytest app /tests/unit /tests/integration /tests/e2e
WARNING: Native build is an experimental feature and could change at any time
Creating cosmic-python_app_run ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 244, in create
    app_module = import_module(app_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'alloc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  (... snip ...)
```

**Comment by dmgolembiowski** [comment]
I'm opening a PR with the fix.
